export type Locale = "he" | "en";

export const content = {
  he: {
    nav: {
      services: "שירותים",
      portfolio: "עבודות",
      rental: "השכרת אתרים",
      blog: "בלוג",
      cta: "שיחת ייעוץ חינם",
      langSwitch: "EN",
      langHref: "/en",
    },
    hero: {
      h1: "אנחנו בונים דיגיטל",
      h1Accent: "שמביא תוצאות.",
      sub: "עיצוב אתרים, חנויות אונליין, קידום אורגני ושיווק במייל לעסקים בישראל. איכות פרימיום, בלי שטויות.",
      cta: "קבעו שיחה חינם",
      ctaSecondary: "לשירותים שלנו",
    },
    pillars: {
      label: "מה אנחנו עושים",
      h2: "פתרונות דיגיטליים",
      h2Accent: "מקצה לקצה",
      items: [
        { title: "בנייה", subtitle: "אתרים וחנויות", desc: "אתרים עסקיים וחנויות אונליין מאפס. עיצוב מותאם אישית, מהירות גבוהה, חוויית משתמש שממירה מבקרים ללקוחות." },
        { title: "קידום", subtitle: "SEO ושיווק", desc: "קידום אורגני, שיווק במייל וקמפיינים ממוקדים. אנחנו מביאים תנועה איכותית ומפכים אותה להכנסה." },
        { title: "צמיחה", subtitle: "אסטרטגיה דיגיטלית", desc: "אסטרטגיה שלמה לנוכחות דיגיטלית. מיתוג, תוכן, רשתות חברתיות ואנליטיקה — הכל תחת קורת גג אחת." },
      ],
    },
    services: {
      label: "שירותים ומחירים",
      h2: "מה אנחנו",
      h2Accent: "מציעים",
    },
    whyUs: {
      label: "למה דווקא אנחנו",
      h2: "מה מבדיל",
      h2Accent: "אותנו מכולם",
      items: [
        { title: "פיתוח מואץ עם AI", desc: "תהליך הפיתוח שלנו מבוסס AI ומקצר לוחות זמנים ב-40%. האתר שלכם עולה לאוויר מהר יותר מהמתחרים.", stat: "40%", statLabel: "מהיר יותר" },
        { title: "איכות פרימיום, מחיר הוגן", desc: "תשתית ברמת ענק — עיצוב, ביצועים ואבטחה — במחיר שעסק קטן ובינוני יכול להרשות לעצמו.", stat: "⚡", statLabel: "תמחור תחרותי" },
        { title: "צוות אחד, הכל כלול", desc: "פיתוח, עיצוב, שיווק, SEO, תוכן — צוות אחד שמטפל בהכל. בלי לרדוף אחרי 5 ספקים שונים.", stat: "1", statLabel: "צוות לכל דבר" },
        { title: "ניסיון אמיתי בשטח", desc: "לא סתם בונים אתרים — אנחנו מפעילים עסקים דיגיטליים בעצמנו. יודעים מה עובד ומה בזבוז כסף.", stat: "7+", statLabel: "שנות ניסיון" },
      ],
    },
    portfolio: {
      label: "עבודות נבחרות",
      h2: "פרויקטים",
      h2Accent: "שבנינו",
    },
    cta: {
      h2: "מוכנים להתחיל",
      h2Accent: "לבנות?",
      sub: "בלי מכירות. בלי לחץ. שיחה כנה על מה שהעסק שלכם צריך ואיך אנחנו יכולים לעזור. תוך 24 שעות נחזור עם הצעה מסודרת.",
      btn: "קבעו שיחה חינם",
    },
    footer: {
      contact: "צרו קשר",
    },
  },
  en: {
    nav: {
      services: "Services",
      portfolio: "Work",
      rental: "Website Rental",
      blog: "Blog",
      cta: "Free Consultation",
      langSwitch: "עב",
      langHref: "/",
    },
    hero: {
      h1: "We Build Digital",
      h1Accent: "That Delivers.",
      sub: "Web design, online stores, SEO and email marketing for businesses in Israel. Premium quality, no BS.",
      cta: "Book a Free Call",
      ctaSecondary: "Our Services",
    },
    pillars: {
      label: "What We Do",
      h2: "End-to-End",
      h2Accent: "Digital Solutions",
      items: [
        { title: "Build", subtitle: "Sites & Stores", desc: "Business websites and online stores from scratch. Custom design, blazing speed, UX that converts visitors into customers." },
        { title: "Promote", subtitle: "SEO & Marketing", desc: "Organic ranking, email marketing and targeted campaigns. We bring quality traffic and turn it into revenue." },
        { title: "Grow", subtitle: "Digital Strategy", desc: "Complete digital presence strategy. Branding, content, social media and analytics — everything under one roof." },
      ],
    },
    services: {
      label: "Services & Pricing",
      h2: "What We",
      h2Accent: "Offer",
    },
    whyUs: {
      label: "Why Us",
      h2: "What Sets",
      h2Accent: "Us Apart",
      items: [
        { title: "AI-Powered Development", desc: "Our dev process is AI-native, cutting timelines by 40%. Your site goes live faster than with any competitor.", stat: "40%", statLabel: "Faster" },
        { title: "Premium Quality, Fair Price", desc: "Enterprise-grade infrastructure — design, performance and security — at a price SMBs can afford.", stat: "⚡", statLabel: "Competitive pricing" },
        { title: "One Team, Everything Included", desc: "Dev, design, marketing, SEO, content — one team handles it all. No chasing 5 different vendors.", stat: "1", statLabel: "Team for everything" },
        { title: "Real Field Experience", desc: "We don't just build sites — we run digital businesses ourselves. We know what works and what wastes money.", stat: "7+", statLabel: "Years experience" },
      ],
    },
    portfolio: {
      label: "Selected Work",
      h2: "Projects",
      h2Accent: "We Built",
    },
    cta: {
      h2: "Ready to Start",
      h2Accent: "Building?",
      sub: "No sales pitch. No pressure. An honest conversation about what your business needs and how we can help. We'll get back with a proposal within 24 hours.",
      btn: "Book a Free Call",
    },
    footer: {
      contact: "Contact Us",
    },
  },
};

export const servicesList = {
  he: [
    { slug: "websites", icon: "/images/icons/icon-website.png", title: "אתר עסקי", desc: "אתר מותאם אישית שמשדר מקצועיות ומביא לקוחות. עיצוב פרימיום, מותאם לנייד, מוכן לקידום מהיום הראשון.", price: "₪4,900", label: "החל מ־" },
    { slug: "ecommerce", icon: "/images/icons/icon-ecommerce.png", title: "חנות אונליין", desc: "חנות דיגיטלית מלאה — קטלוג מוצרים, סליקה, ניהול מלאי וקופה ממירה. הכל עובד, הכל מדיד.", price: "₪8,900", label: "החל מ־" },
    { slug: "email-marketing", icon: "/images/icons/icon-email.png", title: "שיווק במייל", desc: "קמפיינים אוטומטיים, סגמנטציה, רצפי מכירה וניתוח ביצועים. הופכים רשימת תפוצה להכנסה קבועה.", price: "₪2,900", label: "לחודש, החל מ־" },
    { slug: "seo", icon: "/images/icons/icon-seo-new.png", title: "קידום אורגני", desc: "אופטימיזציה טכנית, אסטרטגיית מילות מפתח, בניית קישורים ותוכן. תוצאות מדידות, חודש אחרי חודש.", price: "₪2,900", label: "לחודש, החל מ־" },
  ],
  en: [
    { slug: "websites", icon: "/images/icons/icon-website.png", title: "Business Website", desc: "Custom-designed website that radiates professionalism and brings customers. Premium design, mobile-first, SEO-ready from day one.", price: "₪4,900", label: "Starting at" },
    { slug: "ecommerce", icon: "/images/icons/icon-ecommerce.png", title: "Online Store", desc: "Full e-commerce solution — product catalog, payment processing, inventory management and a checkout that converts. Everything works, everything is measurable.", price: "₪8,900", label: "Starting at" },
    { slug: "email-marketing", icon: "/images/icons/icon-email.png", title: "Email Marketing", desc: "Automated campaigns, segmentation, sales sequences and performance analytics. Turn your mailing list into steady revenue.", price: "₪2,900", label: "/mo, starting at" },
    { slug: "seo", icon: "/images/icons/icon-seo-new.png", title: "SEO", desc: "Technical optimization, keyword strategy, link building and content. Measurable results, month after month.", price: "₪2,900", label: "/mo, starting at" },
  ],
};

export const serviceDetails = {
  he: {
    websites: {
      title: "אתר עסקי",
      subtitle: "הנוכחות הדיגיטלית שהעסק שלך מגיע לה",
      description: "אתר עסקי מותאם אישית שלא רק נראה מעולה — אלא עובד בשבילך 24/7. כל אתר שאנחנו בונים מתוכנן להמיר מבקרים ללקוחות, עם ביצועים גבוהים, SEO מובנה ועיצוב שמשדר אמינות.",
      features: [
        { title: "עיצוב מותאם אישית", desc: "לא תבניות. כל אתר מעוצב מאפס בהתאם למותג ולקהל היעד שלך." },
        { title: "מותאם לנייד", desc: "עיצוב רספונסיבי מלא. יותר מ-60% מהגולשים בישראל גולשים מהנייד — האתר שלך חייב להיות מושלם שם." },
        { title: "מהירות גבוהה", desc: "זמני טעינה של פחות מ-2 שניות. אתר מהיר = יותר המרות ודירוג גבוה יותר בגוגל." },
        { title: "SEO מובנה", desc: "אופטימיזציה טכנית מהיום הראשון. Meta tags, Schema markup, sitemap ומבנה URL נכון." },
        { title: "פאנל ניהול", desc: "מערכת ניהול תוכן פשוטה שמאפשרת לך לעדכן תכנים בעצמך, בלי מפתח." },
        { title: "אנליטיקה מלאה", desc: "Google Analytics ו-Search Console מותקנים ומוגדרים. תדע בדיוק מי מבקר ומאיפה." },
      ],
      process: [
        { step: "01", title: "שיחת היכרות", desc: "מבינים את העסק, הקהל והמטרות שלך. 30 דקות שחוסכות חודשים." },
        { step: "02", title: "עיצוב ואישור", desc: "מציגים עיצוב ראשוני. אתה מאשר, מעיר, ואנחנו מדייקים." },
        { step: "03", title: "פיתוח", desc: "בונים את האתר עם הטכנולוגיות הכי מתקדמות. מהיר, מאובטח, מוכן לצמיחה." },
        { step: "04", title: "השקה ותמיכה", desc: "האתר עולה לאוויר. אנחנו כאן לתמיכה שוטפת ולשדרוגים." },
      ],
      price: "₪4,900",
      priceLabel: "החל מ־",
    },
    ecommerce: {
      title: "חנות אונליין",
      subtitle: "הפוך את המוצרים שלך למכונת מכירות דיגיטלית",
      description: "חנות אונליין מלאה שעובדת בשבילך יום ולילה. קטלוג מוצרים, עגלת קניות, סליקה מאובטחת, ניהול מלאי — הכל מוכן למכירות מהיום הראשון.",
      features: [
        { title: "קטלוג מוצרים חכם", desc: "ניהול מוצרים פשוט עם קטגוריות, מסננים, תמונות ווריאציות. הלקוחות מוצאים מה שהם צריכים בשניות." },
        { title: "סליקה מאובטחת", desc: "חיבור לכל ספקי הסליקה בישראל. אשראי, ביט, PayPal, Apple Pay. מאובטח ב-SSL." },
        { title: "ניהול מלאי", desc: "מעקב מלאי אוטומטי. התראות על מוצרים שנגמרים, דוחות מכירות ואנליטיקה." },
        { title: "קופה ממירה", desc: "תהליך רכישה מהיר ופשוט. פחות שלבים = יותר רכישות מושלמות." },
        { title: "אופטימיזציה למובייל", desc: "חנות שנראית ועובדת מעולה בנייד. רוב הקניות בישראל מתבצעות מהטלפון." },
        { title: "דוחות ואנליטיקה", desc: "דשבורד עם נתוני מכירות, התנהגות לקוחות ומעקב המרות בזמן אמת." },
      ],
      process: [
        { step: "01", title: "אפיון החנות", desc: "מבינים את המוצרים, קהל היעד ותהליך המכירה. מתכננים את החוויה." },
        { step: "02", title: "עיצוב ובנייה", desc: "חנות מעוצבת שמותאמת למותג שלך. UX שמוביל לרכישה." },
        { step: "03", title: "חיבור מערכות", desc: "סליקה, משלוחים, מלאי, חשבוניות — הכל מחובר ועובד אוטומטית." },
        { step: "04", title: "השקה ואופטימיזציה", desc: "החנות עולה לאוויר. אנחנו עוקבים ומשפרים המרות באופן שוטף." },
      ],
      price: "₪8,900",
      priceLabel: "החל מ־",
    },
    "email-marketing": {
      title: "שיווק במייל",
      subtitle: "הפוך את הרשימה שלך להכנסה חודשית קבועה",
      description: "שיווק במייל הוא עדיין הערוץ עם ה-ROI הכי גבוה בדיגיטל. אנחנו בונים מערכת אוטומטית שמטפחת לידים, מוכרת ושומרת על לקוחות — בזמן שאתה ישן.",
      features: [
        { title: "רצפי אוטומציה", desc: "סדרות מיילים שרצות לבד — ברוכים הבאים, נטישת עגלה, מכירות חוזרות, הפעלה מחדש." },
        { title: "סגמנטציה חכמה", desc: "מיילים מותאמים לכל קבוצת לקוחות. תוכן רלוונטי = שיעורי פתיחה גבוהים יותר." },
        { title: "עיצוב מקצועי", desc: "תבניות מייל מעוצבות שמשדרות מקצועיות ומותאמות למותג שלך." },
        { title: "A/B Testing", desc: "בדיקת כותרות, תוכן ועיתוי. נדע בדיוק מה עובד ונכפיל את זה." },
        { title: "ניתוח ביצועים", desc: "דוחות מפורטים — פתיחות, קליקים, המרות, הכנסות. כל מייל מדיד." },
        { title: "ניהול רשימה", desc: "ניקוי רשימה אוטומטי, ניהול הרשמות וביטולים, ציות ל-GDPR." },
      ],
      process: [
        { step: "01", title: "אפיון ואסטרטגיה", desc: "מבינים את הקהל, המוצרים ומטרות המכירה. בונים תוכנית מייל שנתית." },
        { step: "02", title: "הקמת מערכת", desc: "חיבור פלטפורמת מייל, ייבוא רשימות, הגדרת סגמנטים ואוטומציות בסיסיות." },
        { step: "03", title: "יצירת תוכן", desc: "כתיבה ועיצוב של סדרות מיילים, תבניות קמפיין ותוכן שוטף." },
        { step: "04", title: "אופטימיזציה שוטפת", desc: "ניתוח ביצועים חודשי, A/B Testing, שיפור המרות ודוחות." },
      ],
      price: "₪2,900",
      priceLabel: "לחודש, החל מ־",
    },
    seo: {
      title: "קידום אורגני",
      subtitle: "תופיעו בעמוד הראשון — שם שהלקוחות מחפשים",
      description: "קידום אורגני (SEO) הוא ההשקעה הכי חכמה בדיגיטל. תוצאות שנשארות, תנועה חינמית, ולקוחות שמגיעים אליך כי הם חיפשו בדיוק את מה שאתה מציע.",
      features: [
        { title: "אופטימיזציה טכנית", desc: "תיקון מהירות, מבנה אתר, Mobile-first indexing, Core Web Vitals. הבסיס לכל דירוג." },
        { title: "מחקר מילות מפתח", desc: "מיפוי מלא של מה שהלקוחות שלך מחפשים. מילות מפתח עם כוונת רכישה גבוהה." },
        { title: "תוכן ממוקד", desc: "כתיבת עמודים ומאמרים שעונים על שאלות הלקוחות ותופסים מיקומים בגוגל." },
        { title: "בניית קישורים", desc: "קישורים איכותיים מאתרים רלוונטיים שמגבירים את הסמכות של האתר שלך." },
        { title: "SEO מקומי", desc: "אופטימיזציה ל-Google Business Profile, מפות ותוצאות מקומיות. קריטי לעסקים עם נוכחות פיזית." },
        { title: "דוחות חודשיים", desc: "דוח מפורט עם דירוגים, תנועה, המרות ותוכנית פעולה לחודש הבא." },
      ],
      process: [
        { step: "01", title: "אודיט SEO", desc: "בדיקה טכנית מלאה של האתר. מצאנו את כל הבעיות ותיעדפנו לפי השפעה." },
        { step: "02", title: "אסטרטגיה", desc: "תוכנית קידום 6 חודשים — מילות מפתח, תוכן, קישורים ו-KPIs מדידים." },
        { step: "03", title: "ביצוע שוטף", desc: "אופטימיזציה טכנית, יצירת תוכן, בניית קישורים ומעקב דירוגים." },
        { step: "04", title: "ניתוח ושיפור", desc: "דוח חודשי, התאמת אסטרטגיה לפי ביצועים, וזיהוי הזדמנויות חדשות." },
      ],
      price: "₪2,900",
      priceLabel: "לחודש, החל מ־",
    },
  },
  en: {
    websites: {
      title: "Business Website",
      subtitle: "The digital presence your business deserves",
      description: "A custom business website that doesn't just look amazing — it works for you 24/7. Every site we build is engineered to convert visitors into customers, with high performance, built-in SEO and design that radiates credibility.",
      features: [
        { title: "Custom Design", desc: "No templates. Every site designed from scratch to match your brand and target audience." },
        { title: "Mobile-First", desc: "Fully responsive design. Over 60% of users in Israel browse on mobile — your site needs to be perfect there." },
        { title: "Blazing Fast", desc: "Under 2-second load times. A fast site = more conversions and higher Google rankings." },
        { title: "Built-in SEO", desc: "Technical optimization from day one. Meta tags, Schema markup, sitemap and proper URL structure." },
        { title: "CMS Panel", desc: "Simple content management system that lets you update content yourself, no developer needed." },
        { title: "Full Analytics", desc: "Google Analytics and Search Console installed and configured. Know exactly who visits and from where." },
      ],
      process: [
        { step: "01", title: "Discovery Call", desc: "Understanding your business, audience and goals. 30 minutes that save months." },
        { step: "02", title: "Design & Approval", desc: "We present the initial design. You approve, comment, and we refine." },
        { step: "03", title: "Development", desc: "Building the site with cutting-edge technology. Fast, secure, ready to scale." },
        { step: "04", title: "Launch & Support", desc: "The site goes live. We're here for ongoing support and upgrades." },
      ],
      price: "₪4,900",
      priceLabel: "Starting at",
    },
    ecommerce: {
      title: "Online Store",
      subtitle: "Turn your products into a digital sales machine",
      description: "A full online store that works for you day and night. Product catalog, shopping cart, secure payments, inventory management — everything ready to sell from day one.",
      features: [
        { title: "Smart Product Catalog", desc: "Simple product management with categories, filters, images and variations. Customers find what they need in seconds." },
        { title: "Secure Payments", desc: "Connected to all Israeli payment providers. Credit cards, Bit, PayPal, Apple Pay. SSL secured." },
        { title: "Inventory Management", desc: "Automatic stock tracking. Low-stock alerts, sales reports and analytics." },
        { title: "High-Converting Checkout", desc: "Fast and simple purchase flow. Fewer steps = more completed purchases." },
        { title: "Mobile Optimized", desc: "A store that looks and works great on mobile. Most purchases in Israel happen on phones." },
        { title: "Reports & Analytics", desc: "Dashboard with sales data, customer behavior and real-time conversion tracking." },
      ],
      process: [
        { step: "01", title: "Store Scoping", desc: "Understanding products, target audience and sales flow. Planning the experience." },
        { step: "02", title: "Design & Build", desc: "A store designed to match your brand. UX that leads to purchase." },
        { step: "03", title: "System Integration", desc: "Payments, shipping, inventory, invoicing — all connected and automated." },
        { step: "04", title: "Launch & Optimize", desc: "The store goes live. We monitor and improve conversions on an ongoing basis." },
      ],
      price: "₪8,900",
      priceLabel: "Starting at",
    },
    "email-marketing": {
      title: "Email Marketing",
      subtitle: "Turn your list into steady monthly revenue",
      description: "Email marketing is still the highest-ROI channel in digital. We build automated systems that nurture leads, sell and retain customers — while you sleep.",
      features: [
        { title: "Automation Sequences", desc: "Email series that run on autopilot — welcome, cart abandonment, repeat sales, reactivation." },
        { title: "Smart Segmentation", desc: "Emails tailored to each customer group. Relevant content = higher open rates." },
        { title: "Professional Design", desc: "Branded email templates that radiate professionalism and match your brand." },
        { title: "A/B Testing", desc: "Testing subject lines, content and timing. We know exactly what works and double down." },
        { title: "Performance Analytics", desc: "Detailed reports — opens, clicks, conversions, revenue. Every email is measurable." },
        { title: "List Management", desc: "Automatic list cleaning, subscription management, GDPR compliance." },
      ],
      process: [
        { step: "01", title: "Strategy", desc: "Understanding your audience, products and sales goals. Building an annual email plan." },
        { step: "02", title: "System Setup", desc: "Connecting email platform, importing lists, setting up segments and basic automations." },
        { step: "03", title: "Content Creation", desc: "Writing and designing email series, campaign templates and ongoing content." },
        { step: "04", title: "Ongoing Optimization", desc: "Monthly performance analysis, A/B testing, conversion improvement and reports." },
      ],
      price: "₪2,900",
      priceLabel: "/mo, starting at",
    },
    seo: {
      title: "SEO",
      subtitle: "Show up on page one — where your customers are searching",
      description: "SEO is the smartest investment in digital. Results that last, free traffic, and customers who come to you because they searched for exactly what you offer.",
      features: [
        { title: "Technical Optimization", desc: "Speed fixes, site structure, Mobile-first indexing, Core Web Vitals. The foundation for all rankings." },
        { title: "Keyword Research", desc: "Full mapping of what your customers are searching for. High purchase-intent keywords." },
        { title: "Targeted Content", desc: "Writing pages and articles that answer customer questions and capture Google positions." },
        { title: "Link Building", desc: "Quality links from relevant sites that boost your site's authority." },
        { title: "Local SEO", desc: "Google Business Profile optimization, maps and local results. Critical for businesses with physical presence." },
        { title: "Monthly Reports", desc: "Detailed report with rankings, traffic, conversions and next month's action plan." },
      ],
      process: [
        { step: "01", title: "SEO Audit", desc: "Full technical audit of the site. We find all issues and prioritize by impact." },
        { step: "02", title: "Strategy", desc: "6-month SEO plan — keywords, content, links and measurable KPIs." },
        { step: "03", title: "Ongoing Execution", desc: "Technical optimization, content creation, link building and rank tracking." },
        { step: "04", title: "Analysis & Improvement", desc: "Monthly report, strategy adjustment based on performance, and new opportunity identification." },
      ],
      price: "₪2,900",
      priceLabel: "/mo, starting at",
    },
  },
};

export const blogPosts = {
  he: [
    {
      slug: "website-cost-israel-2026",
      title: "כמה עולה לבנות אתר בישראל ב-2026?",
      excerpt: "מדריך מחירים מלא — מאתר תדמית פשוט ועד חנות אונליין מורכבת. מה משפיע על המחיר ואיך לא לשלם יותר מדי.",
      date: "2026-06-18",
      readTime: "5 דק׳",
      category: "מדריכים",
    },
    {
      slug: "seo-basics-small-business",
      title: "SEO לעסקים קטנים — מדריך למתחילים",
      excerpt: "5 דברים שכל בעל עסק יכול לעשות היום כדי להופיע גבוה יותר בגוגל. בלי ידע טכני, בלי תקציב.",
      date: "2026-06-20",
      readTime: "7 דק׳",
      category: "SEO",
    },
    {
      slug: "why-your-website-doesnt-convert",
      title: "למה האתר שלך לא מביא לקוחות (ומה לעשות עם זה)",
      excerpt: "5 סיבות נפוצות שאתרים לא ממירים מבקרים ללקוחות. בדוק את שלך עכשיו.",
      date: "2026-06-23",
      readTime: "4 דק׳",
      category: "המרות",
    },
    {
      slug: "email-marketing-roi",
      title: "שיווק במייל: למה זה עדיין הערוץ הכי רווחי ב-2026",
      excerpt: "ROI של 4,200%. למה עסקים שמזניחים מייל משאירים כסף על השולחן ואיך להתחיל בלי תקציב גדול.",
      date: "2026-06-25",
      readTime: "6 דק׳",
      category: "שיווק",
    },
    {
      slug: "wix-vs-custom-website",
      title: "וויקס מול אתר מותאם אישית — מה עדיף לעסק שלך?",
      excerpt: "השוואה כנה בין בנייה עצמית בפלטפורמה לבין אתר שנבנה במיוחד בשבילך. יתרונות, חסרונות ומתי כל אחד שווה.",
      date: "2026-06-28",
      readTime: "8 דק׳",
      category: "מדריכים",
    },
    {
      slug: "google-business-profile-guide",
      title: "Google Business Profile — המדריך המלא לעסקים בישראל",
      excerpt: "איך להקים, לאופטם ולהפוך את הפרופיל העסקי שלך בגוגל למגנט לקוחות. כולל טיפים לדירוג במפות.",
      date: "2026-07-01",
      readTime: "6 דק׳",
      category: "SEO",
    },
    {
      slug: "shopify-store-not-converting",
      title: "יש לך חנות בשופיפיי ואף אחד לא קונה? ככה מתקנים את זה",
      excerpt: "החנות באוויר, יש תנועה, אבל אף אחד לא מוסיף לעגלה. 7 בעיות נפוצות בחנויות Shopify ואיך לפתור אותן.",
      date: "2026-07-03",
      readTime: "7 דק׳",
      category: "איקומרס",
    },
    {
      slug: "marketplace-to-own-store",
      title: "מוכרים באטסי או בפייסבוק? למה ואיך לעבור לחנות עצמאית",
      excerpt: "מתי להפסיק לסמוך על מרקטפלייסים ולהשיק חנות אונליין משלכם. המדריך המלא למעבר.",
      date: "2026-07-05",
      readTime: "6 דק׳",
      category: "איקומרס",
    },
    {
      slug: "paid-ads-not-working",
      title: "שורפים כסף על פרסום ממומן? 6 סיבות שהמודעות שלכם לא עובדות",
      excerpt: "קמפיינים בפייסבוק או גוגל שמביאים קליקים אבל לא מכירות. 6 בעיות נפוצות ואיך לתקן אותן.",
      date: "2026-07-07",
      readTime: "6 דק׳",
      category: "שיווק",
    },
    {
      slug: "first-customers-online-business",
      title: "איך להשיג את 10 הלקוחות הראשונים לעסק אונליין חדש",
      excerpt: "האתר באוויר אבל אף אחד לא יודע שאתם קיימים. 8 שיטות מעשיות להשיג לקוחות בלי תקציב ענק.",
      date: "2026-07-10",
      readTime: "7 דק׳",
      category: "שיווק",
    },
    {
      slug: "solo-founder-when-to-outsource",
      title: "עושים הכל לבד? מתי הגיע הזמן להוציא החוצה",
      excerpt: "אתם בונים, מעצבים, משווקים ועושים חשבוניות. מדריך מעשי למייסדים שרוצים להפסיק לשרוף את עצמם.",
      date: "2026-07-12",
      readTime: "5 דק׳",
      category: "אסטרטגיה",
    },
  ],
  en: [
    {
      slug: "website-cost-israel-2026",
      title: "How Much Does a Website Cost in Israel in 2026?",
      excerpt: "Complete pricing guide — from a simple landing page to a complex online store. What affects the price and how not to overpay.",
      date: "2026-06-18",
      readTime: "5 min",
      category: "Guides",
    },
    {
      slug: "seo-basics-small-business",
      title: "SEO for Small Businesses — Beginner's Guide",
      excerpt: "5 things any business owner can do today to rank higher on Google. No technical knowledge, no budget required.",
      date: "2026-06-20",
      readTime: "7 min",
      category: "SEO",
    },
    {
      slug: "why-your-website-doesnt-convert",
      title: "Why Your Website Isn't Bringing Customers (And How to Fix It)",
      excerpt: "5 common reasons websites fail to convert visitors into customers. Check yours now.",
      date: "2026-06-23",
      readTime: "4 min",
      category: "Conversions",
    },
    {
      slug: "email-marketing-roi",
      title: "Email Marketing: Why It's Still the Most Profitable Channel in 2026",
      excerpt: "4,200% ROI. Why businesses neglecting email are leaving money on the table and how to start without a big budget.",
      date: "2026-06-25",
      readTime: "6 min",
      category: "Marketing",
    },
    {
      slug: "wix-vs-custom-website",
      title: "Wix vs Custom Website — What's Better for Your Business?",
      excerpt: "An honest comparison between DIY platforms and a custom-built site. Pros, cons and when each one is worth it.",
      date: "2026-06-28",
      readTime: "8 min",
      category: "Guides",
    },
    {
      slug: "google-business-profile-guide",
      title: "Google Business Profile — Complete Guide for Businesses in Israel",
      excerpt: "How to set up, optimize and turn your Google Business Profile into a customer magnet. Including tips for Maps ranking.",
      date: "2026-07-01",
      readTime: "6 min",
      category: "SEO",
    },
    {
      slug: "shopify-store-not-converting",
      title: "Your Shopify Store Gets Traffic but No Sales? Here Is How to Fix It",
      excerpt: "The store is live, traffic is coming in, but nobody adds to cart. 7 common Shopify store problems and how to solve them.",
      date: "2026-07-03",
      readTime: "7 min",
      category: "E-Commerce",
    },
    {
      slug: "marketplace-to-own-store",
      title: "Selling on Etsy or Facebook? Why and How to Move to Your Own Store",
      excerpt: "When to stop relying on marketplaces and launch your own online store. The complete guide to transitioning.",
      date: "2026-07-05",
      readTime: "6 min",
      category: "E-Commerce",
    },
    {
      slug: "paid-ads-not-working",
      title: "Burning Money on Paid Ads? 6 Reasons Your Campaigns Are Not Working",
      excerpt: "Facebook or Google campaigns bringing clicks but not sales. 6 common problems and how to fix them.",
      date: "2026-07-07",
      readTime: "6 min",
      category: "Marketing",
    },
    {
      slug: "first-customers-online-business",
      title: "How to Get Your First 10 Customers for a New Online Business",
      excerpt: "The site is live but nobody knows you exist. 8 practical methods to get your first customers without a huge budget.",
      date: "2026-07-10",
      readTime: "7 min",
      category: "Marketing",
    },
    {
      slug: "solo-founder-when-to-outsource",
      title: "Doing Everything Yourself? When It Is Time to Outsource",
      excerpt: "You build, design, market and do invoices. A practical guide for solo founders who want to stop burning out.",
      date: "2026-07-12",
      readTime: "5 min",
      category: "Strategy",
    },
  ],
};
